-- abbey
-- abbey_stone (abbey.obj)
-- barn
-- broken_fountain
-- cage
-- chicken_coup
-- fountain
-- gazeebo
-- grain_silo
-- house_1 (2,3)
-- house_wood
-- old_house
-- old_spooky_house
-- stone_house
-- water_tower
-- well
-- windmill
